[build]
  base = "platform"
  command = "deno run --allow-read --allow-write scripts/optimise-glyphs.ts && npm run build"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project-id.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
  SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"

[functions]
  directory = "netlify/functions"
