[build]
  base = "platform"
  command = "npm run build"
  publish = "platform/.next"

[build.environment]
  NODE_VERSION = "18"
  SUPABASE_URL = "YOUR_SUPABASE_URL"
  SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
