# Build settings for your Next.js application
[build]
  # Tell Netlify that your app is in the "platform" subfolder.
  base = "platform"

  # The command to build your Next.js site.
  command = "npm run build"

  # The folder that contains the finished site.
  publish = ".next"
