# This configuration file should be at: /platform/netlify.toml

[build]
  # The command to run to build your site.
  # This command is executed from within the /platform directory.
  command = "deno run --allow-read --allow-write scripts/optimise-glyphs.ts"

  # The directory (relative to the /platform directory) that contains
  # the finished site to be deployed.
  publish = "public"

[functions]
  # The directory for your serverless functions, relative to the /platform directory.
  directory = "functions"

