[build]
  base = "platform"
  command = "NEXT_DISABLE_SWC=1 npm run build"
  publish = "platform/.next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':(exclude)docs/**' ':(exclude)scripts/**' ':(exclude)**/*.md'"

[build.environment]
  NEXT_DISABLE_SWC = "1"
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
