[build]
  base = "platform"
  command = "npm run build"
  publish = "platform/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SUPABASE_URL = "https://bjyqsebouppdrgjnpblu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
