[build]
  base    = "platform"
  command = "deno run --allow-read --allow-write scripts/optimise-glyphs.ts && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_SUPABASE_URL = ""      # fill in your Supabase URL
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "" # fill in your Supabase anon key
  SUPABASE_SERVICE_ROLE_KEY = ""     # optional if you use it
