# Build settings for your Next.js application
[build]
  # Tell Netlify that your app is in the "platform" subfolder.
  base = "platform"

  # The command to build your Next.js site.
  # We are only running the essential build command.
  command = "npm run build"

  # The folder that contains the finished site.
  publish = ".next"

# Set a stable Node.js version for the build environment.
[build.environment]
  NODE_VERSION = "20"
