[build]
  base    = "platform"
  command = "npm run build"
  publish = "platform/.next"

  # ✅ Enable caching for faster rebuilds
  environment = { NODE_VERSION = "22" }

[build.environment]
  NODE_VERSION = "22"

# ✅ Cache node_modules and .next between builds
[build.cache]
  paths = [
    "platform/node_modules",
    "platform/.next/cache"
  ]
