[build]
  base = "."
  command = "NEXT_DISABLE_SWC=1 npm run build"
  publish = ".next"

[build.environment]
  NEXT_DISABLE_SWC = "1"
  NODE_VERSION = "22"

# Optional: cache node_modules for faster builds
[build.cache]
  paths = ["node_modules"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
