name: CI

on:
  push:
    branches: [ main, merge-dta ]   # Run on production + staging
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint and Type Check
        run: |
          npm run lint || true
          npm run type-check || true

      - name: Build Next.js app
        run: npm run build

      # Optional: Supabase type generation
      - name: Supabase Typegen
  if: ${{ env.SUPABASE_PROJECT_REF != '' }}
  run: |
    # Use cat to strip any control sequences from CLI output
    supabase gen types typescript \
      --project-id "$SUPABASE_PROJECT_REF" \
      | cat > platform/src/lib/database.types.ts
  env:
    SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
