name: CI

on:
  push:
    branches: [ main, merge-dta ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for committing back

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint and Type Check
        run: |
          npm run lint || true
          npm run type-check || true

      - name: Build Next.js app
        run: npm run build

      # ✅ Supabase typegen runs only on staging branch
      - name: Supabase Typegen (staging only)
        if: github.ref == 'refs/heads/merge-dta'
        run: |
          set -e
          echo "🔄 Running Supabase typegen..."
          if supabase gen types typescript \
            --project-id "$SUPABASE_PROJECT_REF" \
            | cat > platform/src/lib/database.types.ts; then
            echo "✅ Typegen succeeded"

            # Commit changes if file actually changed
            if ! git diff --quiet platform/src/lib/database.types.ts; then
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add platform/src/lib/database.types.ts
              git commit -m "chore: update Supabase types [skip ci]"
              git push origin merge-dta
            else
              echo "ℹ️ No changes in database.types.ts"
            fi
          else
            echo "⚠️ Supabase typegen failed, keeping existing types"
          fi
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
