name: Generate Supabase Types

on:
  workflow_dispatch: # allow manual runs
  push:
    branches: [ main ] # regenerate on pushes to main

jobs:
  gen-types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Install Supabase CLI
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # ✅ Debug: show project ref (safe to log)
      - run: echo "Using Supabase project ref: ${{ secrets.SUPABASE_PROJECT_REF }}"

      # ✅ Ensure secrets exist before running CLI
      - name: Verify secrets
  run: |
    if [ -z "${{ secrets.SUPABASE_PROJECT_REF }}" ]; then
      echo "❌ Missing SUPABASE_PROJECT_REF secret"
      exit 1
    fi
    if [ -z "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ]; then
      echo "❌ Missing SUPABASE_ACCESS_TOKEN secret"
      exit 1
    fi

    # Masked previews (safe logging)
    echo "✅ SUPABASE_PROJECT_REF is set (starts with: ${SUPABASE_PROJECT_REF:0:4}****)"
    echo "✅ SUPABASE_ACCESS_TOKEN is set (starts with: ${SUPABASE_ACCESS_TOKEN:0:4}****)"

    echo "✅ All required secrets are present"
  env:
    SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
