name: Generate Supabase Types

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  gen-types:
    runs-on: ubuntu-latest

    # Make secrets available to every step (simplifies env handling)
    env:
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # Set up Node (includes built-in npm cache)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Install Supabase CLI
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Verify secrets (with masked preview)
      - name: Verify secrets
        shell: bash
        run: |
          if [ -z "$SUPABASE_PROJECT_REF" ]; then
            echo "❌ Missing SUPABASE_PROJECT_REF secret"
            exit 1
          fi
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "❌ Missing SUPABASE_ACCESS_TOKEN secret"
            exit 1
          fi
          echo "✅ Using SUPABASE_PROJECT_REF: ${SUPABASE_PROJECT_REF:0:4}****"
          echo "✅ SUPABASE_ACCESS_TOKEN is set"

      # Generate types into the file in your app
      - name: Generate database types
        shell: bash
        run: |
          supabase gen types typescript \
            --project-id "$SUPABASE_PROJECT_REF" \
            > platform/src/lib/database.types.ts

      # Commit only if the file actually changed
      - name: Commit changes if any
        shell: bash
        run: |
          if git diff --quiet platform/src/lib/database.types.ts; then
            echo "✅ No changes in database.types.ts — skipping commit."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add platform/src/lib/database.types.ts
            git commit -m "chore: update Supabase types"
            git push
          fi
