name: Generate Supabase Types

on:
  workflow_dispatch: # allow manual runs
  push:
    branches: [ main ] # regenerate on pushes to main

jobs:
  gen-types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Cache node_modules (speeds up installs)
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ✅ Set up Node.js (match your Netlify env, e.g. Node 22)
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # ✅ Install Supabase CLI
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # ✅ Debug: show project ref (safe to log)
      - name: Debug project ref
        run: echo "Using Supabase project ref: ${{ secrets.SUPABASE_PROJECT_REF }}"

      # ✅ Ensure secrets exist before running CLI
      - name: Verify secrets
        run: |
          if [ -z "${{ secrets.SUPABASE_PROJECT_REF }}" ]; then
            echo "❌ Missing SUPABASE_PROJECT_REF secret"
            exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ]; then
            echo "❌ Missing SUPABASE_ACCESS_TOKEN secret"
            exit 1
          fi

          # Masked previews (safe logging)
          echo "✅ SUPABASE_PROJECT_REF is set (starts with: ${SUPABASE_PROJECT_REF:0:4}****)"
          echo "✅ SUPABASE_ACCESS_TOKEN is set (starts with: ${SUPABASE_ACCESS_TOKEN:0:4}****)"
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # ✅ Generate types into file
      - name: Generate database types
        run: supabase gen types typescript --project-id ${{ secrets.SUPABASE_PROJECT_REF }} > platform/src/lib/database.types.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # ✅ Commit only if file changed
      - name: Commit changes if any
        run: |
          if git diff --quiet platform/src/lib/database.types.ts; then
            echo "✅ No changes in database.types.ts — skipping commit."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add platform/src/lib/database.types.ts
            git commit -m "chore: update Supabase types"
            git push
          fi
