name: Test Secrets

on:
  workflow_dispatch:   # run manually from GitHub Actions tab

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print which secrets are set
        run: |
          for secret in \
            SUPABASE_PROJECT_REF \
            SUPABASE_ACCESS_TOKEN \
            NETLIFY_BUILD_HOOK_PROD \
            NETLIFY_BUILD_HOOK_STAGING \
            NETLIFY_BUILD_HOOK_PREVIEW \
            NETLIFY_SITE_ID \
            NETLIFY_AUTH_TOKEN; do
              if [ -n "${!secret}" ]; then
                echo "✅ $secret is available"
              else
                echo "❌ $secret is missing"
              fi
          done
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          NETLIFY_BUILD_HOOK_PROD: ${{ secrets.NETLIFY_BUILD_HOOK_PROD }}
          NETLIFY_BUILD_HOOK_STAGING: ${{ secrets.NETLIFY_BUILD_HOOK_STAGING }}
          NETLIFY_BUILD_HOOK_PREVIEW: ${{ secrets.NETLIFY_BUILD_HOOK_PREVIEW }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
